django_project_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("diary/", include("diary.urls")),
    path("picnic/", include("plp.urls")),
    path("spelling/", include("spelling.urls")),
    path("calcy/", include("calco.urls")),
    #path("squares/", include("squaresg.urls")),
    path("", include("squaresg.urls")),
    
#     path("", include("squaresg.urls")),
#     path("spelling/", include("spelling.urls")),
#     path('admin/', admin.site.urls),
]

# handler404 = "squaresg.views.handler404"
# handler500 = "squaresg.views.error_500"

plp/urls.py
from django.urls import path
from . import views2

app_name = "plp"

urlpatterns = [
    path("submity/",views2.subbo, name="submity"),
    path("", views2.picn, name="index"),
    ]

spelling/urls.py
from django.urls import path
from . import views

app_name = "spelling"

urlpatterns = [
    #path("", views.ShowTweets.as_view(), name="index"),
    path("", views.searchy, name="index"),
    path("to_send/", views.sure, name="to_send"),
    path("sending_tweet/", views.sendy, name="sending"),
    path("wordypick/", views.wordPick, name="wordpicking"),
    path("filtdown/", views.filterdown, name="filtdown"),
    path("filtup/", views.filterup, name="filtup"),
    path("voted/", views.closey, name="voted_already"),
    path("about/", views.about, name="about"),
    ]

spelling/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Tub(models.Model):
    the_text = models.CharField(max_length=200, default="")
    def __str__(self):
        return self.the_text

class Admonish(models.Model):
    adm_id = models.IntegerField(default=0)
    adm_term = models.CharField(max_length=200, default="")
    adm_text = models.CharField(max_length=280, default="")
    #adm_seshn = models.CharField(max_length=200, default="")
    def __str__(self):
        return self.adm_text

class TweetLists(models.Model):
    twe_dict = models.CharField(max_length=50000, default="")
    twe_term = models.CharField(max_length=20, default="")
    twe_seshn = models.CharField(max_length=200, default="")
    #twe_time = models.DateTimeField(default=datetime.datetime.now(datetime.timezone.utc))
    twe_time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.twe_seshn

spelling/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from .models import Tub, Admonish, TweetLists
from .logico.tweepy_process import cookie_help, cookie_help_2, getty, send_tweet, api, make_id, get_answers, \
     lookup_answer, readie, make_lists, get_lists, page_turn
from .service import cleanup
import json, datetime


# Create your views here.

def wordPick(request):
    chosen = request.POST.get("wordpicking")
    cookey = request.COOKIES.get("chosen", chosen)
    response = HttpResponseRedirect(reverse("spelling:index"))
    response.set_cookie("chosen", chosen)
    return response

def searchy(request):
    nowy = datetime.datetime.now(datetime.timezone.utc)
    
    if not "seshn" in request.COOKIES:
        seshn = cookie_help(request.COOKIES, "seshn", make_id())
    else:
        seshn = request.COOKIES["seshn"]
    
    checking = TweetLists.objects.filter(twe_seshn=seshn, twe_term="thye").values_list("twe_time")
    
    if "seshn" in request.COOKIES and not TweetLists.objects.filter(twe_seshn=seshn, twe_term="thye").exists():
        make_lists(seshn)
    
    if checking.exists() and nowy - checking[0][0] > timedelta(minutes=20):
        TweetLists.objects.filter(twe_seshn=seshn).all().delete()
        make_lists(seshn)
        
    whichp = "1 - 5"
    if "chosen" in request.COOKIES:
        wordu = request.COOKIES["chosen"]
    else:
        wordu = "blanku"
    rcooki = cookie_help(request.COOKIES, "risp", "START!")
    
    if "chosen" in request.COOKIES and request.COOKIES["chosen"] != "blanku":
        dicty2 = get_lists(wordu, seshn)
    else:
        dicty2 = [[[{"":"","":"","":"","":"","":""}],[]],[]]
    
    if "answers" in request.COOKIES:
        cookie_words = request.COOKIES["answers"]
        vocab = readie(cookie_words)
    else:
        vocab = get_answers()
        cookie_words = request.COOKIES.get("answers", vocab)
                
    clicked = request.GET.get("tweety_id")
    
    if wordu != "blanku":
        words = lookup_answer(vocab[wordu], wordu)
        get_text = "".join([i["tweet_text"] for i in dicty2 if i["tweet_id"] == str(clicked)])
    else:
        words = ""
        get_text = ""
    
    clicked3 = request.GET.get("screen_name")

    boxo = request.GET.get("boxo")
    marker = cookie_help(request.COOKIES, "boxo", boxo)
    cookey = cookie_help(request.COOKIES, "namey", clicked3)
    gus = cookie_help(request.COOKIES, "filtery", str(1))
    dicty2, whichp = page_turn(gus, whichp, dicty2)
    
    
    conetext = {"tweets":dicty2, "gus":gus, "whichp":whichp, "wordu":wordu,
                "words":words, "clicked": clicked, "the_text":get_text, "clicked3":clicked3, "boxo": boxo}
    response = render(request, "spelling/index.html", conetext)
    cleanup(request, response)
    response.set_cookie("seshn", seshn)
    response.set_cookie("filtery", gus)
    response.set_cookie("chosen", wordu)
    response.set_cookie("risp", rcooki)
    response.set_cookie("namey", clicked3)
    response.set_cookie("answers", cookie_words)
    response.set_cookie("boxo", boxo)
    return response

def filterup(request):
    response = HttpResponseRedirect(reverse("spelling:index"))
    numbu = cookie_help_2(request.COOKIES, "filtery", str(1), int(request.COOKIES["filtery"]))
    response.set_cookie("filtery", str(numbu + 1))
    return response

def filterdown(request):
    response = HttpResponseRedirect(reverse("spelling:index"))
    numbu = cookie_help_2(request.COOKIES, "filtery", str(1), int(request.COOKIES["filtery"]))
    response.set_cookie("filtery", str(numbu - 1))
    return response


def sure(request):
    template = "spelling/index.html"
    clicked = request.GET.get("tweety_id")

    gursp = clicked
    wordu = request.COOKIES["chosen"]
    gus = request.COOKIES["filtery"]
    context = {"gus": gus, "wordu": wordu}

    cooki = cookie_help(request.COOKIES, "sesho", make_id())

    response = render(request, template, context)
    response.set_cookie("sesho", cooki)
    response.set_cookie("risp", "Two bloo")
    return response

def sendy(request):
    cookie_words = request.COOKIES["answers"]
    vocab = readie(cookie_words)
    wordu = request.COOKIES["chosen"]
    word = lookup_answer(vocab[wordu], wordu)
    clicked = request.GET.get("tweety_id")
    gursp = clicked
    context = {"clicked":clicked}
    send_tweet(word, gursp)
    response = HttpResponseRedirect(reverse("spelling:index"))

    cooko = cookie_help(request.COOKIES, "done", clicked)

    response.set_cookie("done", clicked)
    response.set_cookie("risp", "THANK!")

    return response


def closey(request):
    response = HttpResponseRedirect(reverse("spelling:index"))
    response.set_cookie("risp", "STOP!")
    response.set_cookie("boxo", "FALSE")
    return response

def about(request):
    response = render(request, "spelling/about_spelling.html", {})
    return response

spelling/templates/spelling/about_spelling.html
<header>About This Project</header>
{% extends "base.html" %}
{% load static %}

</head>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fredoka&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Space&+ono" rel="stylesheet">

<meta name="viewport" content="width=device-width, initial-scale=1.0" />

{% block content %}

<body>

<div class="hello"><a href="{% url "spelling:index" %}"><u>Back to project</u></a></div><br>
<div class="hello" style="width: 90%; margin: auto;">This app connects to the Twitter API and allows you to both find and correct a stranger's spelling error.<br><br>
There is always a chance that my Twitter API access could be revoked if an irritated tweeter complains about having their spelling corrected. Just in case that ever happens, here is a step-by-step 
guide to how this app works. 
<br><br>
<span style="color: #000294;"><p>
<b>1. For demo purposes, I wrote my own poorly-spelt tweet with a common typo:<br>
<img style="width: 300px;" src="https://i.ibb.co/NSvqjZg/Screenshot-20220322-183046-Twitter.jpg" alt="Screenshot-20220322-183046-Twitter" border="0" /></p>
<p>
2. On the app, choose a typo to search - let's go with 'Realyl':<br>
<img style="width: 300px;" src="https://i.ibb.co/Yc9XzmC/Screenshot-20220725-222535-Samsung-Internet.jpg" alt="Screenshot-20220322-183153-Samsung-Internet" border="0" />
</p>
<p>
3. Choose my tweet from the search results:<br>
<img style="width: 300px;" src="https://i.ibb.co/CQzB3dG/Screenshot-20220322-183159-Samsung-Internet.jpg" alt="Screenshot-20220322-183159-Samsung-Internet" border="0" />
</p>
<p>
4. The pre-written riposte can be seen here. You can't write your own response, because you could simply go on Twitter for that. 
Plus, this way I know that the replies sent from this app won't ever be very offensive!<br>
<img style="width: 300px;" src="https://i.ibb.co/9yXPPW3/Screenshot-20220322-183221-Samsung-Internet.jpg" alt="Screenshot-20220322-183221-Samsung-Internet" border="0" />
</p>
<p>5. The reply has been sent! Would you like to see it in the wild?<br>
<img style="width: 300px;" src="https://i.ibb.co/THfr85r/Screenshot-20220322-183244-Samsung-Internet.jpg" alt="Screenshot-20220322-183244-Samsung-Internet" border="0" />
</p>
<p>6. There it is! That'll teach me.<br>
<img style="width: 300px;" src="https://i.ibb.co/KNG0t3h/Screenshot-20220322-183309-Samsung-Internet.jpg" alt="Screenshot-20220322-183244-Samsung-Internet" border="0" />

</p>
<p>7. Telling the same person off twice are we? Nice try! Thanks to a cookie that I've set, you cannot reply to anyone more than once. 
This aims to keep the complaints to a minimum.</b><br>
<img style="width: 300px;"  src="https://i.ibb.co/yht1k9r/Screenshot-20220322-183322-Samsung-Internet.jpg" alt="Screenshot-20220322-183322-Samsung-Internet" border="0" />
</p></span>


</div>

<div class="hello"><a href="{% url "spelling:index" %}"><u>Back to project</u></a></div>

</body>

{% endblock content %}

spelling/templates/spelling/index.html
<header>Twitter Spelling Police</header>
{% extends "base.html" %}
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fredoka&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Space&+ono" rel="stylesheet">

<meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>

{% block content %}


<body>

<div class="hello"><a href="{% url "spelling:about" %}"><u>How this app works</u></a></div>

{% block javascript %}
<script type="text/javascript">
function openBox() {
 document.getElementById("boxy").style.display = "block";
 return true;
}
</script>

<script type="text/javascript">
function closeBox() {
 document.getElementById("boxy").style.display = "none";
}
</script>
{% endblock %}



<div class="controls" id="radios">
<!-- Radio buttons for word picking-->
<form action="{% url "spelling:wordpicking" %}" method="POST">{% csrf_token %}
 <div>
  
  
  <div class="leftside"><label>
  {% if wordu == "againts" or wordu == "blanku" %}
   <input type="radio" class="inputy" name="wordpicking" id="againts" value="againts" checked>
  {% else %}
   <input type="radio" class="inputy" name="wordpicking" if="againts" value="againts">
  {% endif %}
  Againts</label></div>
  

  <div class="chooseo"><label>
  {% if wordu == "alwyas" %}
   <input type="radio" class="inputy" name="wordpicking" id="alwyas" value="alwyas" checked>
  {% else %}
   <input type="radio" class="inputy" name="wordpicking" id="alwyas" value="alwyas">
  {% endif %}
  Alwyas</label></div>
  

  <div class="rightside"><label>
  {% if wordu == "becasue" %}
   <input type="radio" class="inputy" name="wordpicking" id="becasue" value="becasue" checked>
  {% else %}
   <input type="radio" class="inputy" name="wordpicking" id="becasue" value="becasue">
  {% endif %}
  Becasue</label></div>
<br>

  <div class="leftside"><label>
  {% if wordu == "firend" %}
   <input type="radio" class="inputy" name="wordpicking" id="firend" value="firend" checked>
  {% else %}
   <input type="radio" class="inputy" name="wordpicking" id="firend" value="firend">
  {% endif %}
  Firend</label></div>
  

  <div class="chooseo"><label>
  {% if wordu == "realyl" %}
   <input type="radio" class="inputy" name="wordpicking" id="realyl" value="realyl" checked>
  {% else %}
   <input type="radio" class="inputy" name="wordpicking" id="realyl" value="realyl">
  {% endif %}
  Realyl</label></div>
  

  <div class="rightside"><label>
  {% if wordu == "thye" %}
   <input type="radio" class="inputy" name="wordpicking" id="thye" value="thye" checked>
  {% else %}
   <input type="radio" class="inputy" name="wordpicking" id="thye" value="thye">
  {% endif %}
  Thye</label></div>
<br>

  
  <input type="submit" value="Submit" id="searchy">
 </div>
</form>
</div>




{% if wordu == "blanku" %}
  <div class="hello">Please select a typo!</div>
{% else %}


<div class="pages">
{% if gus > "1" %}
<a href="{% url "spelling:filtdown" %}" id="prev5">
Prev 5</a>&nbsp;&nbsp;|&nbsp;&nbsp

{% else %} 
{% endif %}

{{ whichp }}

{% if gus < "6" %}
&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="{% url "spelling:filtup" %}" id="next5">
Next 5 
</a>
{% else %}
{% endif %}
</div>


{% for res in tweets %}

<div class="the_tweets" id="tweet{{ forloop.counter }}" onclick="openBox();">
 <a href="{% url "spelling:index" %}?tweety_id={{ res.tweet_id | urlencode }}
&tweety_text={{ res.tweet_text | urlencode }}
&screen_name={{ res.their_username | urlencode }}&boxo=TRUE" name="{{ res.tweet_id }}">




  <strong><div class="deets-left">@{{ res.their_username }}</div><div class="deets-right"><i>{{ res.tweet_date }}</i></div></strong><!--</div>-->
  <div class="deets-bottom">{{ res.tweet_text }}</div>



 </a>
</div>


{% endfor %}





<div class="pages">
{% if gus > "1" %}
 <a href="{% url "spelling:filtdown" %}" id="prev5">
Prev 5</a>&nbsp;&nbsp;|&nbsp;&nbsp;

{% else %}
{% endif %}


{{ whichp }}

{% if gus < "6" %}
&nbsp;&nbsp;|&nbsp;&nbsp;
 <a href="{% url "spelling:filtup" %}" id="next5">
Next 5 
 </a>
{% else %}
{% endif %}


{% endif %}
</div>







{% if boxo == "TRUE" or request.COOKIES.risp == "THANK!" %}
<div id="boxy" style="display: block;">
{% else %}
<div id="boxy" style="display: none;">
{% endif %}


{% if request.COOKIES.risp == "THANK!" %}

<h2>You have sent your Tweet!</h2>
<p><a href="https://twitter.com/{{ request.COOKIES.namey }}/status/{{ request.COOKIES.done }}/" target="#">View it here.</a></p>

<p class="closer"><a href="{% url "spelling:voted_already" %}">Close (x)</a></p>


{% elif request.COOKIES.risp == "STOP!" %}

<h3><i>You have already tweeted!</i></h3>
<p class="closer" id="lastclose"><a href="{% url "spelling:index" %}?boxo=FALSE">Close (x)</a></p>

{% elif request.COOKIES.risp == "START!" %}




<p class="inst">Your Tweet:</p>
<p class="words1"><i>{{ words }}</i></p>
<p class="inst">Replying To:</p>
<p class="words2"><i>{{ the_text }}</i></p>

<p class="inst">Send Reply?</p>
<div id="the_buttons"><a href="{% url "spelling:sending" %}?tweety_id={{ clicked | urlencode }}&boxo=TRUE" name="clicked">Submit</a>  |  
<a href="{% url "spelling:index" %}?boxo=FALSE">Cancel</a></div></p>


{% endif %}
</div>


</body>
{% endblock content %}