calco/urls.py
from django.urls import path
from . import views

app_name = "calco"

urlpatterns = [
    path("first/", views.first, name="first"),
    path("colour/", views.colour_pick, name="colour"),
    path("", views.calc1, name="calc1"),
    path("key_process/", views.key_process, name="key_process"),
    ]

diary/urls.py
from django.urls import path
from . import views

app_name = "diary"

urlpatterns = [
    path("<int:pk>/", views.DetailEntryView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DeleteEntryView.as_view(), name="delete"),
    path("<int:pk>/edit2/", views.UpdateEntryView2, name="edit2"),
    path("new/", views.NewEntryView2, name="new"),
    path("search/", views.searching, name="searchy"),
    path("clear_query/", views.clear_query, name="clear_query"),
    path("all/", views.search_all, name="search_all"),
    path("email/", views.send_emails, name="emails"),
    path("hideo/", views.hideo, name="hideo"),
    path("backo/", views.back_to_before, name="back_before"),
    path("", views.EntryListView2, name="home"),
    path("about/", views.about_diary, name="about_diary"),
    ]

django_project_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("diary/", include("diary.urls")),
    path("picnic/", include("plp.urls")),
    path("spelling/", include("spelling.urls")),
    path("calcy/", include("calco.urls")),
    #path("squares/", include("squaresg.urls")),
    path("", include("squaresg.urls")),
    
#     path("", include("squaresg.urls")),
#     path("spelling/", include("spelling.urls")),
#     path('admin/', admin.site.urls),
]

# handler404 = "squaresg.views.handler404"
# handler500 = "squaresg.views.error_500"

plp/urls.py
from django.urls import path
from . import views2

app_name = "plp"

urlpatterns = [
    path("submity/",views2.subbo, name="submity"),
    path("", views2.picn, name="index"),
    ]

spelling/urls.py
from django.urls import path
from . import views

app_name = "spelling"

urlpatterns = [
    #path("", views.ShowTweets.as_view(), name="index"),
    path("", views.searchy, name="index"),
    path("to_send/", views.sure, name="to_send"),
    path("sending_tweet/", views.sendy, name="sending"),
    path("wordypick/", views.wordPick, name="wordpicking"),
    path("filtdown/", views.filterdown, name="filtdown"),
    path("filtup/", views.filterup, name="filtup"),
    path("voted/", views.closey, name="voted_already"),
    path("about/", views.about, name="about"),
    ]

squaresg/urls.py
from django.urls import path
from . import views
import django

app_name = "squaresg"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("squares/", views.SquaresView2, name="squares"),
    path("squaresn/", views.RandomSquaresView, name="squares_rand"),
    path("squaresr/", views.resetty, name="resetto"),
    path("squaresr2/", views.resetty2, name="resetto2"),
    path("squaresr3/", views.resetty3, name="resetto3"),
    path("saveIt/", views.Scoresy, name="scoresyform"),
    path("projects/", views.ProjectsView, name="projects"),
    ]

squaresg/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


# Create your models here.

class Scores(models.Model):
    namey = models.CharField(default="", max_length=9)
    score = models.IntegerField(default=0)
    duration = models.CharField(default = "blank", max_length=30)
    all_seconds = models.IntegerField(default=0)
    attempts = models.IntegerField(default=0)
    def __str__(self):
        return self.namey
    
    def get_duration(self):
        return self.finish_time - self.start_time

squaresg/forms.py
from django import forms
from .models import Scores

# class ChoiceForm(forms.ModelForm):
# 
#     class Meta:
#         model = Choice
#         choice_text = "Geeseys"
#         votes = 0
#         fields = ["choice_text",]
#         labels = {"choice_text":"New Choice"}

class ScoreForm(forms.ModelForm):
    
    class Meta:
        model = Scores
        namey = "Type Your Name"
        #score = 0
        fields = ["namey",]
        labels = {"namey":"Type Your Name"}

squaresg/views.py
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.template import loader, RequestContext
from django.template.response import TemplateResponse
from django.views import generic
from django.utils import timezone
from django.db.models import Count
from django.views.generic.edit import FormMixin
from .forms import ScoreForm
from .service import make_list_for_view, randomise_squares, \
     initial_cou, datechange, cleanup2
from .logico.squares_logic import cookie_help, cookie_help_2, randular
from .models import Scores
from datetime import date, time, datetime, timedelta
import ast

# Create your views here.

class IndexView(generic.ListView):
    template_name = "squaresg/index.html"
    context_object_name = "a_queryset"
    
    def get_queryset(self):
        queryset = Scores.objects.none()
        return queryset

def resetty(request):
    resety = int(request.COOKIES["resety"])
    resety += 1
    numboure, excepe = make_list_for_view()
    cou = initial_cou(numboure)

    goesy = cookie_help(request, "goesy", 0)
    response = HttpResponseRedirect(reverse("squaresg:squares"))
    response.set_cookie("resety", resety)
    response.set_cookie("goesy", 0)
    response.set_cookie("squores", numboure)
    response.set_cookie("excepor", excepe)
    response.set_cookie("cou", cou)
    
    return response

def resetty3(request):
    response = HttpResponseRedirect(reverse("squaresg:squares"))
    if "squores" in request.COOKIES:
        numboure = request.COOKIES["squores"]
        excepe = request.COOKIES["excepor"]
        cou = request.COOKIES["cou"]
    else:
        numboure, excepe = make_list_for_view()
        cou = initial_cou(numboure)
    starty_time = cookie_help(request, "starty_time", "BEGIN!")
    finishy_time = cookie_help(request, "finishy_time", 0)
    goesy = cookie_help(request, "goesy", 0)
    resety = cookie_help(request, "resety", 0)
    
    cleanup2(request, response)
    response.set_cookie("squores", numboure)
    response.set_cookie("excepor", excepe)
    response.set_cookie("goesy", goesy)
    response.set_cookie("resety", resety)
    response.set_cookie("starty_time", starty_time)
    response.set_cookie("finishy_time", finishy_time)
    response.set_cookie("cou", cou)
    return response
    

def resetty2(request):
    response = HttpResponseRedirect(reverse("squaresg:squares"))
    request.session.set_test_cookie()
    numboure, excepe = make_list_for_view()
    cou = initial_cou(numboure)
    squores = cookie_help(request, "squores", numboure)
    goesy = cookie_help(request, "goesy", 0)
    resety = cookie_help(request, "resety", 0)
    finishy_time = cookie_help(request, "finishy_time", 0)
    starty_time = cookie_help(request, "starty_time", "BEGIN!")
    
    cleanup2(request, response)
    response.set_cookie("squores", numboure)
    response.set_cookie("excepor", excepe)
    response.set_cookie("goesy", 0)
    response.set_cookie("resety", 0)
    response.set_cookie("starty_time", "BEGIN!")
    response.set_cookie("finishy_time", 0)
    response.set_cookie("cou", cou)
    
    return response

def SquaresView2(request):
    template = "squaresg/squares.html"
    form = ScoreForm
    scores = Scores.objects.all().order_by("score","all_seconds","attempts").values()[:10]
    if "squores" in request.COOKIES and "excepor" in request.COOKIES and "cou" in request.COOKIES and "goesy" in request.COOKIES:
        numboure = ast.literal_eval(request.COOKIES["squores"])
        excepe = int(request.COOKIES["excepor"])
        cou = request.COOKIES["cou"]
        turny = request.COOKIES["goesy"]
        context = {"cou":cou, "exceppo":excepe, "form":form, "scores":scores, "nine_squares_list": numboure, "goes": turny}
    else:
        context = {"scores":scores}
    return render(request, template, context)
    

def RandomSquaresView(request):
    essence = ["squores", "cou", "goesy", "excepor", "starty_time", \
               "finishy_time", "resety"]
    for e in essence:
        if e not in request.COOKIES:
            return HttpResponseRedirect(reverse("squaresg:squares"))

    numbourey = ast.literal_eval(request.COOKIES["squores"])
    excepe = int(request.COOKIES["excepor"])
    turny = int(request.COOKIES["goesy"])
    if "cou" in request.COOKIES and request.COOKIES["cou"] == "WIN":
        turny = turny
    else:
        turny += 1
    
    form = ScoreForm
    
    scores = Scores.objects.all().order_by("score", "all_seconds", "attempts").values()[:10]
    clicked = request.GET.get("square_id")
    
    listy2 = numbourey
    nine_squares_list = numbourey
    numbourey, cou = randomise_squares(listy2, excepe, clicked, request)
    
    url = "squaresg/squares.html"

    if cou == "WIN":
        numbourey = [1,2,3,4,5,6,7,8,9]
    elif numbourey == [1,2,3,4,5,6,7,8,9]:
        cou = "WIN"

    context = {"nine_squares_list":numbourey, "cou":cou, "goes":turny,
           "exceppo":excepe, "form":form, "scores":scores}    
    if request.method == "POST" and "squares_rand" in request.POST:
        response = HttpResponseRequest(reverse("squaresg:squares"))

        response.set_cookie("squores", numbourey)
        response.set_cookies("goesy", turny)
        response.set_cookies("cou", cou)
        if request.COOKIES["starty_time"] == "BEGIN!":
            response.set_cookie("starty_time", datetime.now())
        response.set_cookie("finishy_time", datetime.now())
        return response
    else:
        response = HttpResponseRedirect(reverse("squaresg:squares"))
        response.set_cookie("squores", numbourey)
        response.set_cookie("goesy", turny)
        response.set_cookie("cou", cou)
        if request.COOKIES["starty_time"] == "BEGIN!":
            response.set_cookie("starty_time", datetime.now())
        response.set_cookie("finishy_time", datetime.now())
        return response

def get_time(request):
    tok = datetime.strptime
    dura = datechange(request.COOKIES["finishy_time"], tok) - \
           datechange(request.COOKIES["starty_time"], tok)
    
    days = dura.days
    hours = int(dura.seconds*3600)
    hours2 = round(int(dura.seconds/3600),0)
    seconds = int(round(dura.seconds%60,0))
    minutes = int(round(dura.seconds/60,0))
    seconds2 = dura.seconds
    attempts = request.COOKIES["resety"]
    if hours2 < 1:
        duration = str(hours2).zfill(2) + ":" + str(minutes).zfill(2) + ":" + str(seconds).zfill(2)
    elif days == 1:
        duration = str(days) + " day " + str(hours2).zfill(2) +":" + str(minutes).zfill(2) + ":" + str(seconds).zfill(2)
    elif hours2 >=1 and days < 1:
        duration = str(hours2).zfill(2) + ":" + str(minutes).zfill(2) + ":" + str(seconds).zfill(2)
    elif days > 1:
        duration = str(days) + " days " + str(hours2).zfill(2) + ":" + str(minutes).zfill(2) + ":" + str(seconds).zfill(2)
    elif days > 7:
        duration = str("FAILURE")
    
    return duration, seconds2, attempts

def Scoresy(request, *args, **kwargs):
    if request.method == "POST" and "saveIt" in request.POST:
        form = ScoreForm(request.POST)
        
        if form.is_valid():
            scores2 = int(request.COOKIES["goesy"])
            duration, seconds2, attempts = get_time(request)
            form.instance.score = int(scores2)
            form.instance.duration = str(duration)
            form.instance.all_seconds = int(seconds2)
            form.instance.attempts = int(attempts)
            form.instance.duration = duration
            form.save()
            return HttpResponseRedirect(reverse("squaresg:resetto2"))
    else:
        form = ScoreForm()
    return render(request, "squaresg/squares.html", {"form":form})

def ProjectsView(request):
    template="squaresg/projects.html"
    context = {}
    return render(request, template, context)

squaresg/templates/squaresg/index.html
<header>My Django Djourney</header>
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "squaresg/style.css" %}" >
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>

{% block content %}

<div class="missingPiece" style="padding-left: 5px; padding-right: 5px; padding-top: 10px;">Hello and welcome to my online portfolio! 
My name is Nick Hart and I am looking to move into web develpment with Django.<br><br>
This portfolio features five projects (so far) that I have been working on this year.  
These showcase my Django learning journey, and demonstrate my curiosity, inventiveness and problem-solving abilities.<br><br>
You can view the Github repo for these projects <a href="https://github.com/nicknicknick4444/portfolio" target="#">here</a>.
</div>


<!--<p style="font-size: 11px; padding-left: 15px; padding-right: 15px;">I have been learning to program on and off for several years, but made a serious go of learning python in January 2021. 
Since then I have practised every day, working my way through six books (three on the topic of python, and three Django.)
<br><br>
To this end, I have created some Django projects that demonstrate what I have learnt.<br><br>
Upon finishing the Django books I felt something was missing from the tutorials: business logic. Beyong list views, logins and blog apps, I wanted to <i>make</i> things from my own imagination.
<br><br>Starting with DJango's own Polls app tutorial, I began experimenting, which soon led me onto a whole new road of learning. Before I knew it, I was out on my own, leaving the tutorials behind and following my imagination.<br><br>
I picked up a lot of vital skills while working in the resulting projects, such a function views, the use of cookies for persistence, pagination and the consumption of web APIs.<br><br>
The discovery of function views was a particular turning point, since they satisfied my desire to move beyond ready-made class views. And once I found I could send a word or a number to the template, 
I reaslised I could send a calculated value, or the output of an API, or the returned values of a whole suporting cast of helper functions...
<br><br>
My curiosity and self-learning has led me to create some projects. Some are fun and some are light-hearted; some are serious and downright useful. 
All of them represent great leaps forward not only in my knowledge of Django, but of the python programming language in general. 
<br><br>Please have a look at my projets - see if you can sort the numbers game into the correct order; find the best <i>and</i> worst places in the UK for a picnic do some sums on a customised calculator; 
or even lecture a total stranger on Twitter for their sloppy spelling!<br><br>
I hope you enjoy trying them out. I have a strong desire to become a profesional Django developer, and these projects aim to demonstrate that passion.
<br><br>Be sure to have a look at all my code for these projects on <a href="https://github.com/nicknicknick4444/portfolio">Github</a>.
</p>-->
<!--<div class="my_links" style="text-align: center; font-size: 30px;"><a href="{% url "squaresg:resetto2" %}">9 Squares</a>
<br><br>
<a href="{% url "spelling:index" %}">Spelling Police</a>
<br><br>
<a href="{% url "plp:index" %}">Picnic Location Planner</a>
<br><br>
<a href="{% url "diary:home" %}">Diary Emailer</a>
<br><br>
<a href="{% url "calco:calc1" %}">Calculators</a>
</div>-->

{% endblock content %}

squaresg/templates/squaresg/projects.html
<header>My Projects</header>
{% extends "base.html" %}
{% load static %}
<!--<link rel="stylesheet" type="text/css" href="{% static "squaresg/style.css" %}" >-->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>

{% block content %}


<div class="my_links" style="text-align: center; font-size: 30px;"><a href="{% url "squaresg:resetto3" %}">9 Squares</a>
<br><br>
<a href="{% url "spelling:index" %}">Twitter Spelling Police</a>
<br><br>
<a href="{% url "plp:index" %}">Picnic Location Planner</a>
<br><br>
<a href="{% url "diary:home" %}">Diary Emailer</a>
<br><br>
<a href="{% url "calco:calc1" %}">Calculators</a>
</div>


{% endblock content %}

squaresg/templates/squaresg/squares.html
<header>9 Squares Game</header>
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "squaresg/style.css" %}" >
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>



<!--<h1>Helloo!</h1>-->

{% block content %}


<body>

{% block javascript %}
<script type="text/javascript">
function getScore() {
 document.getElementById("scoreBoard").style.display = "block";
}
</script>

<script type="text/javascript">
function hideScore() {
 document.getElementById("scoreBoard").style.display = "none";
}
</script>

<script>
function getSave() {
 document.getElementById("saveScore").style.display = "block";
 document.getElementById("gameOptions").style.display = "none";
}
</script>

<script>
function hideSave() {
 document.getElementById("saveScore").style.display = "none";
 document.getElementById("gameOptions").style.display = "block";
}
</script>

{% endblock %}





{% with A=request.COOKIES %}
{% if "squores" in A and "cou" in A and "goesy" in A and "excepor" in A and "starty_time" in A and "finishy_time" in A and "resety" in A %}



<div class="missingPiece">

{% if cou == "WIN" %}
 <a href="{% url "squaresg:resetto2" %}">Reset | 
{% else %}
 <a href="{% url "squaresg:resetto" %}">Reset</a> | 
{% endif %}
<a href="#" onclick="getScore();return false;">Leaderboard</a>
</div>
<div class="missingPiece">Put the squares into numerical order (l-r).<br>Click on a square to slide it into the space.</div>












<!--<br>-->

{% if cou == "WIN" %}
 <div class="rowWin">
{% else %}
 <div class="row">
{% endif %}


{% for squ in nine_squares_list %}

 {% if squ in cou %}

  <!--<div class="column"><a href="{% url "squaresg:squares_rand" %}?square_id={{ squ | urlencode }}"><div class="overhov"></div><img src="../static/squaresg/images/{{ squ }}"></a>-->
  <a href="{% url "squaresg:squares_rand" %}?square_id={{ squ | urlencode }}"><span class="numbers"><div class="column"><span class="spu">{{ squ }}</span></div></span></a>
  

 {% else %}

  {% if squ == "blank" %}
   <div class="blanko"></div>
  {% else %}

  <!--<div class="column"><img src="../static/squaresg/images/{{ squ }}">-->
   <span class="numbers2"><div class="column"><span class="spu">{{ squ }}
  </span></div></span>
  {% endif %}
 {% endif %}
{% endfor %}
</div>

<!--<br>-->

{% if cou == "WIN" %}
 <div class="missingPiece">You did it! Number of winning moves: {{ goes }}</div>
 <div class="missingPiece" id="gameOptions">
  <a href="#" onclick="getSave();return false;">Save Score</a> | 
  <!--<a href="{% url "squaresg:resetto2" %}">Play Again</a></div>-->
  <a href="{% url "squaresg:resetto2" %}">Play Again</a></div>
{% else %}
 <div class="missingPiece"><!--Move the numbers into order and win the -->Missing Piece:<br>
<!--<img src="../static/squaresg/images/{{ exceppo }}" id="missingPiece">-->
 <div id="missingPiece"><span class="spu2">{{ exceppo }}</span></div>

</div>

{% endif %}

<div id="scoreBoard">
<div style="width: 100%;float: left; text-align: right;"><a href="#" onclick="hideScore();return false;">(Close)</a></div>
<p id="top10"><b>Top Winners</b></p>
 <div style="padding-bottom: 10px;">
  <div class="scoreLeft" id="full"><strong>Rank/ Name</strong></div>
  <div class="scoreMidL" id="full"><strong>Moves</strong></div>
  <div class="scoreMidR" id="full"><strong>Resets</strong></div>
  <div class="scoreRight" id="full"><strong>Time</strong></div>

 </div>

{% for sk in scores %}
 <div>
 <div class="scoreLeft"><!--<span id="small"><strong>Name:  </strong></span>-->{{ forloop.counter }}: {{ sk.namey|title }}</div>
 <div class="scoreMidL"><span id="small"><strong>Moves: </strong></span>{{ sk.score }}</div>
 <div class="scoreMidR"><span id="small"><strong>Resets: </strong></span>{{ sk.attempts }}</div>
 <div class="scoreRight"><span id="small"><strong>Time: </strong></span>{{ sk.duration }}</div>
</div>
{% endfor %}

<!--<div style="width: 100%;float: left;"><a href="#" onclick="hideScore();return false;">(Close)</a></div>-->
</div>


<!--{% if cou == "WIN" %}

{% else %}
 
{% endif %}-->

<div id="saveScore" class="row" style="text-align: center;" style="display:block;">
<form id="formy" action="{% url "squaresg:scoresyform" %}" method="POST">{% csrf_token %}
 <fieldset>
  {{ form.as_p }}
  <input type="submit" name="saveIt" value="Save & Play Again">
  <input type="button" value = "Cancel" onclick="hideSave()";return false;">
 </fieldset>
</form>
</div>







{% else %}





<div class="missingPiece">
<!--<a href="{% url "squaresg:index" %}">Home</a>
{% if cou == "WIN" %}
 <a href="{% url "squaresg:resetto2" %}">Reset
{% else %}
 <a href="{% url "squaresg:resetto" %}">Reset</a>
{% endif %}
<a href="#" onclick="getScore();return false;">Leaderboard</a>-->
</div>







<a href="{% url "squaresg:resetto2" %}">
 <div class="pad"><span id="playGame">PLAY GAME</span></div>
</a>

<!--<div id="scoreBoard">
<div style="width: 100%;float: left; text-align: right;"><a href="#" onclick="hideScore();return false;">(Close)</a></div>
<p id="top10"><b>Top Winners</b></p>
 <div style="padding-bottom: 10px;">
  <div class="scoreLeft" id="full"><strong>Rank/ Name</strong></div>
  <div class="scoreMidL" id="full"><strong>Moves</strong></div>
  <div class="scoreMidR" id="full"><strong>Resets</strong></div>
  <div class="scoreRight" id="full"><strong>Time</strong></div>

 </div>-->

{% endif %}
{% endwith %}



</body>


{% endblock content %}