accounts/urls.py
from django.urls import path
from .views import SignUpView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup")
    ]

diary/urls.py
from django.urls import path
from . import views

app_name = "diary"

urlpatterns = [
    path("<int:pk>/", views.DetailEntryView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DeleteEntryView.as_view(), name="delete"),
    path("<int:pk>/edit2/", views.UpdateEntryView2, name="edit2"),
    path("new/", views.NewEntryView2, name="new"),
    path("search/", views.searching, name="searchy"),
    path("clear_query/", views.clear_query, name="clear_query"),
    path("all/", views.search_all, name="search_all"),
    path("email/", views.send_emails, name="emails"),
    path("hideo/", views.hideo, name="hideo"),
    path("backo/", views.back_to_before, name="back_before"),
    path("", views.EntryListView2, name="home"),
    path("about/", views.about_diary, name="about_diary"),
    ]

django_project_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("diary/", include("diary.urls")),
    path("picnic/", include("plp.urls")),
    path("spelling/", include("spelling.urls")),
    path("calcy/", include("calco.urls")),
    #path("squares/", include("squaresg.urls")),
    path("", include("squaresg.urls")),
    
#     path("", include("squaresg.urls")),
#     path("spelling/", include("spelling.urls")),
#     path('admin/', admin.site.urls),
]

# handler404 = "squaresg.views.handler404"
# handler500 = "squaresg.views.error_500"

plp/urls.py
from django.urls import path
from . import views2

app_name = "plp"

urlpatterns = [
    path("submity/",views2.subbo, name="submity"),
    path("", views2.picn, name="index"),
    ]

diary/forms.py
from django import forms
from django.forms import Form, ModelForm, DateField, ModelMultipleChoiceField, \
     PasswordInput, EmailInput
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
#from django.forms.extras.widgets import SelectDateWidget
from .models import Entry, SendTime
from functools import partial
#from django.forms.widgets import DateInput

# class DateInput(forms.DateInput):
#     input_type="date"


# YEAR_CHOICES = ["2022","2023","2024"]
# MONTH_CHOICES = ["04", "05"]
# DAY_CHOICES = ["01", "02"]

class UserChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.first_name
    
#DateInput = partial(forms.DateInput, {"class":"datepicker"})

queryo = User.objects.values_list("first_name", flat=True)
queryo2 = User.objects.values_list("first_name", "last_name")
#que2 = [((i for i in que) i in que) for i in que]
print([(i,i) for i in queryo])
print([i for i in queryo2])
#print(que2)

class NewEntryForm(ModelForm):
#     def __init__(self, *args, **kwargs):
#         super(NewEntryForm, self).__init__(*args, **kwargs)
#         self.fields["user"] = forms.ModelMultipleChoiceField(queryset=User.objects.filter(username__startswith="M"))
    
    user = forms.ChoiceField(choices=queryo)
    #user = UserChoiceField
    #forms.ChoiceField.input_type="select"
    #forms.ChoiceField( choices=tuple_of_tuples)
    #user = forms.CharField(widget=forms.Textarea())
    
    #queryset = User.objects.filter(username__startswith="M")
    #print(queryset)
#     def get_form(self, request, obj, **kwargs):
#         form = super(NewEntryForm, self).get_form(request, obj, **kwargs)
#         form.base_fields["user"] = forms.ModelChoiceField(queryset)
#         print("PASTE!")
#         return form
    
    #form["user"] = forms.ModelChoiceField(queryset)
    #print(user)
    forms.DateInput.input_type="date"
    
    print("PAPER!", User.objects.filter(first_name__startswith="M"))
    #print("PAPYRUS!", User.objects.all(), to_field_name="first_name")
#     def __init__(self, *args, **kwargs):
#         super(NewEntryForm, self).__init__(*args, **kwargs)
#         self.fields["user"].initial = self.instance.user.first_name
#         
#     def save(self, *args, **kwargs):
#         super(NewEntryForm, self).save(*args, **kwargs)
#         self.instance.user.first_name = self.cleaned_data.get("first_name")
#         self.instance.user.save()
    
    class Meta:
        model = Entry
        #borce = MyModelChoiceField(queryset=Entry.objects.all())
        fields = "__all__"
        exclude = ("by", "mod_by", "date_written")
    
#        def __init__(self, *args, **kwargs):
#             super(NewEntryForm, self).__init__(*args, **kwargs)
#             self.fields["user"].queryset = User.objects.all()
#             self.fields["user"].label_from_instance = lambda obj: obj.first_name
        
class CreateUserForm(ModelForm):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=PasswordInput)
    email = forms.CharField(widget=EmailInput)
    first_name = forms.CharField(max_length=100, label="Name")
    last_name_ = forms.CharField(max_length=100, label="Initial")
    
    class Meta:
        model = User
        fields = ["username", "password", "email", "first_name", "last_name"]

# class MyUserChangeForm(UserChangeForm):
#     def __init__(aelf, *args, **kwargs):
#         super(MyUserChangeForm, self).__init__(*args, **kwargs)
#     
#         self.fields["first_name"].required = True

class SetTimeForm(forms.Form):
    HOUR_OPTIONS = [("01", "1am"), ("02", "2am"), ("03", "3am"), ("04", "4am"), ("05", "5am"), ("06", "6am"),
                    ("07", "7am"), ("08", "8am"), ("09", "9am"), ("10", "10am"), ("11", "11am"), ("12", "12am"),
                    ("13", "1pm"), ("14", "2pm"), ("15", "3pm"), ("16", "4pm"), ("17", "5pm"), ("18", "6pm"),
                    ("19", "7pm"), ("20", "8pm"), ("21", "9pm"), ("22", "10pm"), ("23", "11pm"), ("00", "12pm")]
    MINUTE_OPTIONS = [("00", "00"), ("15", "15"), ("30", "30"), ("45", "45")]
    #hour = forms.CharField(label="Hour", widget=forms.Select(choices=HOUR_OPTIONS))
    #minute = forms.CharField(label="Minute", widget=forms.Select(choices=MINUTE_OPTIONS))
    hour = forms.ChoiceField(choices=HOUR_OPTIONS)
    minute = forms.ChoiceField(choices=MINUTE_OPTIONS, initial="00")
    #proto_send_time = "".join((send_time, ":", minute))
    #print(proto_send_time)
    #send_time = 
    
    class Meta:
        #model = SendTime
        fields = ["hour", "minute"]

# class SearchForm(forms.Form):
#     class Meta:
#         termy = forms.CharField(max_length=1000, default="")


class UpdateViewForm(forms.ModelForm):
    query_list = User.objects.values_list("first_name", "last_name")
    USER_CHOICES = [i for i in query_list]
    user = forms.ChoiceField(choices = USER_CHOICES)

    class Meta:
        model = Entry
        fields = ("title",
              "detail",
              "user",
              "date_for")
    

        

diary/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, \
     DetailView, TemplateView
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from .models import Entry, SendTime
from .forms import NewEntryForm, CreateUserForm, SetTimeForm, UpdateViewForm
from .service import convert_date, cookie_help, search_change_help, user_change_help, \
                    date_change_help, filter_func, today, cookie_eat
from .email_send import main as email_main

# Create your views here.

def EntryListView2(request):
    object_list_raw = Entry.objects.all().order_by("date_for", "user", "title")
    
    object_list = [i for i in object_list_raw if i.is_old == False]
    user_query = User.objects.values_list("first_name", "last_name")
    USER_CHOICES2 = [i for i in user_query]
    template = "diary/list_entries.html"
    
    paginator = Paginator(object_list, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    response = render(request, template, {"today": today(), "object_list": page_obj,
                                      "users_list": USER_CHOICES2})

    cookie_eat(request.COOKIES, response)
    return response

def searching(request):
    user_query = User.objects.values_list("first_name", "last_name")
    USER_CHOICES2 = [i for i in user_query]
    users_list = [i for i in USER_CHOICES2]
    query_s = request.POST.get("term_search")
    query_u = request.POST.get("sort_user")
    if query_u == None:
        query_u = ""

    raw_query_d = request.POST.get("by_date")
    
    if "query_d" not in request.COOKIES:
        if raw_query_d != "":
            query_d = convert_date(raw_query_d)
        elif raw_query_d == "":
            query_d = ""
        else:
            query_d = ""
    else:
        query_d = ""
          
    query_s = cookie_help(request.COOKIES, "query_s", query_s)
    query_u = cookie_help(request.COOKIES, "query_u", query_u)
    query_d = cookie_help(request.COOKIES, "query_d", query_d)

    if request.method == "POST" or "query_s" in request.COOKIES:
            
        query_s = search_change_help(request.method, request.COOKIES, "query_s", request.POST.get("term_search"), query_s)
        if "query_u" in request.COOKIES:
            query_u = user_change_help(request.COOKIES, "query_u", request.POST.get("sort_user"), request.method, request.COOKIES["query_u"])
         
        query_d = date_change_help(request.COOKIES, "query_d", request.POST.get("by_date"))        
        que3 = filter_func(query_s, query_u, query_d)
    
    if len(que3) == 0:
        searcho = "EMPTY!"
    else:
        searcho = "SEARCHING!"
    saved = ""
    
    que3 = [i for i in que3]
    
    #Pagination
    paginator = Paginator(que3, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    response =  render(request, "diary/list_entries.html", {"searchu": searcho, "object_list": page_obj,
                                                        "today": today(), "users_list": USER_CHOICES2,
                                                       "word_query": query_s, "user_query": query_u,
                                                       "date_query": query_d, "saved": saved,
                                                       "page_obj": page_obj, })
    response.set_cookie("query_s", query_s)
    response.set_cookie("query_u", query_u)
    response.set_cookie("query_d", query_d)
    return response

def clear_query(request):
    cleared_query_raw = Entry.objects.all().order_by("date_for", "user", "title")
    cleared_query = [i for i in cleared_query_raw if i.is_old == False]
    saved = ""
    user_query = User.objects.values_list("first_name", "last_name")
    USER_CHOICES2 = [i for i in user_query]
    users_list = [i for i in USER_CHOICES2]
    searcho = "CLEARED!"
    template = "diary/list_entries.html"
    
    paginator = Paginator(cleared_query, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    response = render(request, template, {"searchu": searcho, "object_list": page_obj,
                                        "today": today(), "users_list": USER_CHOICES2,
                                      "saved": saved,})    
    cookoes = ["query_s", "query_u", "query_d"]
    for i in cookoes:
        response.delete_cookie(i)
       
    return response

class DetailEntryView(DetailView):
    model = Entry
    template_name="diary/detail_entry.html"
    
    def render_to_response(self, context, **response_kwargs):
        response = super(DetailView, self).render_to_response(context, **response_kwargs)
        refero = self.request.META.get("HTTP_REFERER")
        urly = cookie_help(self.request.COOKIES, "URLY", refero)
        response.set_cookie("URLY", refero)
        return response

class DeleteEntryView(LoginRequiredMixin, DeleteView):
    model = Entry
    template_name = "diary/delete_entry.html"
    success_url = reverse_lazy("diary:home")
    success_message = "Deleted!"
    
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteEntryView, self).delete(request, *args, **kwargs)
    
    def render_to_response(self, context, **response_kwargs):
        response = super(DeleteView, self).render_to_response(context, **response_kwargs)
        refero = self.request.META.get("HTTP_REFERER")
        urly = cookie_help(self.request.COOKIES, "URLY", refero)
        response.set_cookie("URLY", refero)
        return response
    
@login_required
def NewEntryView2(request):
    user_query = User.objects.values_list("first_name", "last_name")
    USER_CHOICES2 = [i for i in user_query]
    new_title = request.POST.get("new_title")
    new_detail = request.POST.get("new_detail")
    new_user = request.POST.get("new_user")
    new_date = request.POST.get("new_date")
    curr_user = request.user.first_name
    
    refero = request.META.get("HTTP_REFERER")
    urly = cookie_help(request.COOKIES, "URLY", refero)
    
    template = "diary/new_entry.html"
    context = {"users_list": USER_CHOICES2}
    response = render(request, template, context)
    if request.method == "POST":
        if convert_date(new_date) >= datetime.datetime.now().date():
            Entry.objects.create(title=new_title, detail=new_detail, \
                                        user=new_user, date_for=convert_date(new_date), \
                                 created=today(), last_modified=today(), \
                                 mod_by=curr_user, by=curr_user)
            messages.success(request, "Entry saved!")
            return HttpResponseRedirect(reverse("diary:home"))
        else:
            context = {"users_list": USER_CHOICES2, "signal": "Date can't be in the past!"}
            
            response.set_cookie("URLY", refero)
            return response
    else:
        response.set_cookie("URLY", refero)
        return response

@login_required
def UpdateEntryView2(request, pk):
    user_query = User.objects.values_list("first_name", "last_name")
    USER_CHOICES2 = [i for i in user_query]
    the_entry = get_object_or_404(Entry, pk=pk)
    title = request.POST.get("edit_title")
    detail = request.POST.get("edit_detail")
    user = request.POST.get("edit_user")
    date = request.POST.get("edit_date")
    
    template = "diary/edit_entry.html"
    context = {"title": title, "detail": detail,
                                      "user": user, "date": date,
                                      "entry": the_entry, 
                                      "users_list": USER_CHOICES2,
                                      "selected_user": the_entry.user}

    refero = request.META.get("HTTP_REFERER")
    urly = cookie_help(request.COOKIES, "URLY", refero)
    
    if request.method == "POST":
        if convert_date(date) >= datetime.datetime.now().date():
            the_entry.title = title
            the_entry.detail = detail
            the_entry.user = user
            the_entry.mod_by = request.user.first_name
            the_entry.date_for = convert_date(date)
            the_entry.last_modified = today()
            the_entry.save()
            
            all_entries = Entry.objects.all().order_by("date_for")
            messages.success(request, "Entry updated!")
            response = HttpResponseRedirect(reverse("diary:back_before"))
            return response
        else:
            context = {"title": title, "detail": detail, "user": user, "date": date,
                       "entry": the_entry, "users_list": USER_CHOICES2,
                       "selected_user": the_entry.user, "signal": "Date can't be in the past!"}
            response = render(request, template, context)
            return response
    else:
        response = render(request, template, context)
        response.set_cookie("URLY", refero)
        return response

def search_all(request):
    all_entries = Entry.objects.all().order_by("date_for")
    user_query = User.objects.values_list("first_name", "last_name")
    USER_CHOICES2 = [i for i in user_query]
    searcho = "SEARCHING!"
    template = "diary/list_entries.html"
    return render(request, template, {"object_list": all_entries, "users_list": USER_CHOICES2,
                                      "all_query": "ALL!", "today": today(), "searchu": searcho,
                                      "word_query": "", "user_query": None, "date_query": ""})

diary/templates/diary/add_user.html
<header>Add User</header>
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="page_contents">

{% if saved != "SAVED!" %}

<form action="{% url "diary:add_user" %}" method="POST" name="CreateUserForm" value="add_user">{% csrf_token %}

{{ form.as_p }}

<br>
<button type="submit">Create</button>&nbsp;&nbsp;|&nbsp;&nbsp;
<button><a href="{% url "diary:home" %}">Cancel</a></button>
</form>

{% endif %}

</div>

{% endblock content %}

diary/templates/diary/delete_entry.html
<!-- diary/delete_entry.html -->
<header>Delete Entry</header>
{% extends "base.html" %}
{% load static %}


{% block content %}


<div class="page_contents">

<b><a style="float: right;" href="{% url "logout" %}">Log Out&nbsp;&nbsp;&nbsp;</a></b><br>


 <form action="" method="POST">{% csrf_token %}
<div class="deleting_detail">
  <div>Are you sure you want to delete this diary entry entitled "{{ entry.title }}"?</div>

  <div class="gap"></div>
   <button class="btn btn-danger ml-2" type="submit">Confirm Delete</button>
   <button><a href="{% url "diary:back_before" %}">Cancel</a></button> 
</div>
</form>

</div>
{% endblock content %}

diary/templates/diary/detail_entry.html
<!-- diary/detail_entry.html -->
<header>View Entry</header>
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="page_contents">

{% if user.is_authenticated %}
 <!--<input type="hidden" name="next" value="{{ request.path }}">
 <a href="{% url "logout" %}">Log Out</a></input>-->

<b><a style="float: right;" href="{% url "logout" %}">Log Out&nbsp;&nbsp;&nbsp;</a></b><br>

{% endif %}

<div class="deleting_detail" style="padding-top: 0; padding-left: 3px; padding-right: 3px;">
 <div style="font-size: 30px;">{{ entry.title }}</div>
 <p>Emailing Date: {{ entry.date_for }}</p>
 <p>For: {{ entry.user }}</p>
 <p>Detail: {{ entry.detail }}</p>
 <p style="font-size: 10px;">(Date Added: {{ entry.created }}) by {{ entry.by }}</p> 
 <p style="font-size: 10px;">(Last Modified: {{ entry.last_modified }}) by {{ entry.mod_by }}</p>

<button><a href="{% url "diary:back_before" %}">Back to main list</a></button>
</div>


<!--{% if user.is_authenticated %}
 Or <button><a href="{% url "diary:delete" entry.pk %}">Delete</a></button>
{% endif %}-->


</div>

{% endblock content %}

diary/templates/diary/done.html
{% extends "base.html" %}

{% block content %}
<h1>Done!</h1>
<a href="{% url "diary:home" %}">Back</a>
{% endblock content %}

diary/templates/diary/home2.html
<!-- templates/registration/home.html -->
{% extends "base.html" %}

{% block title %}Welcome{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
Welcome! Head to the <a href="{% url "diary:home" %}">diary.</a>
<br>
Wrong way? <a href="{% url "logout" %}">Log Out</a> please.
{% else %}

 <p>You are not logged in!</p>
 <a href="{% url "login" %}">Log In</a>  |  
 <a href="{% url "accounts:signup" %}">Sign Up Please<a/>

{% endif %}

{% endblock content %}

diary/templates/diary/list_entries.html
<header>Diary Emailer</header>
{% extends "base.html" %}
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>


{% block content %}

<body>




<div class="page_contents">






<div class="hello" style="margin-bottom: 5px;"><a href="{% url "diary:about_diary" %}"><u>How this app works</u></a></div>
{% if user.is_authenticated %}

<!-- FOR EMAIL TESTING -->
{% if "sent_signal" in request.COOKIES %}
 <button disabled="disabled">Sent</button>
{% else %}
 <button><a href="{% url "diary:emails" %}">Send</a></button>
{% endif %}

&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url "diary:new" %}">+New Entry</a>



 &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url "logout" %}">Log Out</a>

{% else %}

 &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url "login" %}">Log In</a>

{% endif %}
</div>
<div class="gap"></div>
<div class="page_contents">
Today is {{ today }}
<div class="gap"></div>

<!--{% if saved == "SAVED!" %}
 <p>
  User saved successfully!<br>
 </p>
{% endif %}-->

{% if searchu == "SEARCHING!" or searchu == "EMPTY!" and searchu != "CLEARED!" %}
 {% if word_query != "" %}
  <div>Searching for: {{ word_query }}</div>
 {% endif %}
 {% if user_query != "" %}
  <div>Filtering by user: {{ user_query }}</div>

 {% endif %}
 {% if date_query != "" %}
  <div>Filtering by date: {{ date_query }}</div>
 {% endif %}

<!--<p></p>-->

{% endif %}



{% if "vanisho" not in request.COOKIES %}

 <form action="{% url "diary:searchy" %}" method="POST" name="s" value="s">{% csrf_token %}
 <div class="form_style" style="padding-right: 3px;">
  <label class="labelo2">Search:</label><input style="width: 170px;" type="text" name="term_search"></input>
  <!--<button type="submit">Search</button> Search: --><br>
<div class="gap"></div>
<div style="text-align: left;">User Filter:</div>
<div class="user_contain" style="width: 282px; height: 40px;">
{% for the_user in users_list %}

 <div class="user_col" style="width: 87px; height: 15px; float: left;">
  
 
  
{% comment %}
    {% if user_query == the_user.0 %}
     <input type="radio" class="input_u" name="sort_user", value="{{ query_name }}" checked>
    
     
    {% else %}

     <input type="radio" class="input_u" name="sort_user" value="{{ the_user.0 }}">
{% endcomment %}

 <label class="labelo3"><input type="radio" class="input_u" name="sort_user" value="{{ the_user.0 }}">
 {{ the_user.0 }}</label>

  <!--</label>--><br>
 </div>

{% endfor %}
</div>

<div class="gap" style="height: 20px;"></div>

<label class="labelo2">Pick Date:</label>
 <input name="by_date" type="date" id="date_pick">

<br><br>
<div style="padding-right: 31px;">
 <button type="submit"">Search & Filter</button></div>
 <!--<button><a href="{% url "diary:search_all" %}">Search All</a></button>-->
</div>
</form>



<div class="toggleo"><a href="{% url "diary:hideo" %}">HIDE FILTERS</a><br></div>

{% elif "vanisho" in request.COOKIES %}
 {% if "query_d" in request.COOKIES %}
<div class="toggleo" style="padding-top: 9px;"><a href="{% url "diary:hideo" %}">SHOW FILTERS</a></div>
 {% else %}

<div class="toggleo"><a href="{% url "diary:hideo" %}">SHOW FILTERS</a></div>

 {% endif %}

{% endif %}

</div>

	{% if searchu == "SEARCHING!" and searchu != "CLEARED!" %}
<div class="page_contents">

<button style="margin-bottom: 10px;"><a href="{% url "diary:clear_query" %}">Clear</a></button><br>
<!--{{ searchu }}<br>-->
</div>
	{% endif %}


{% if searchu == "SEARCHING!" or searchu == "CLEARED!" or searchu == "USER_ADDED!" %}

<div class="page_contents">

{% if messages %}
 {% for message in messages %}
   <div style="margin: auto; display: block; text-align: center;">
    <strong>
     {{ message }}
    </strong>
 {% endfor %}
{% endif %}

{% for find in object_list %}

{% if find.is_old %}

<div class="entry">
<a href="{% url "diary:detail" find.pk %}">
<strong>{{ find.date_for }}<br>{{ find.title }}</strong><br>
{{ find.detail|truncatechars:25 }}<br>
For: {{ find.user }}</a><br><div class="gap"></div>
 <a href="{% url "diary:detail" find.pk %}">View Entry</a>
{% if user.is_authenticated %}
  |  
 <a href="{% url "diary:delete" find.pk %}">Delete Entry</a>
<!--</div>-->


{% endif %}
</div>

<br><!--<br>-->

{% else %}

  <div class="entry">
<a href="{% url "diary:detail" find.pk %}">
<strong><i>{{ find.date_for }}</i><br>{{ find.title }}</strong><br>
{{ find.detail|truncatechars:25 }}<br>
For: {{ find.user }}</a><br><div class="gap"></div>
<a href="{% url "diary:detail" find.pk %}">View Entry</a><br>
{% if user.is_authenticated %}
 <a href="{% url "diary:edit2" find.pk %}">Edit Entry</a>  |  
 <a href="{% url "diary:delete" find.pk %}">Delete Entry</a>


{% endif %}

</div>


<br><!--<br>-->

{% endif %}

{% endfor %}

</div>

{% elif searchu == "EMPTY!" %}

<div class="page_contents">0 diary entries found.<br><br>
<button><a href="{% url "diary:clear_query" %}">Clear</a></button><br><br>
</div>


{% else %}


{% if messages %}
 {% for message in messages %}
 <div style="margin: auto; display: block; text-align: center;">
 <strong>
  {{ message }}
 </strong>
 </div>
 {% endfor %}
{% endif %}
<!--<br>-->

<div class="listo">
{% for entry in object_list %}

{% if entry.is_old %}



{% else %}

<div class="entry">
<a href="{% url "diary:detail" entry.pk %}">
<strong><i>{{ entry.date_for }}</i><br>
{{ entry.title }}</strong><br>
{{ entry.detail|truncatechars:25 }}<br>
For: {{ entry.user }}</a><br><div class="gap"></div>
<a href="{% url "diary:detail" entry.pk %}">View Entry</a><br> 
{% if user.is_authenticated %}
 <a href="{% url "diary:edit2" entry.pk %}">Edit Entry</a>  |  
 <a href="{% url "diary:delete" entry.pk %}">Delete Entry</a>
</div>
<br><!--<br>-->
{% else %}
</div>
<br>
{% endif %}



{% endif %}

{% endfor %}


{% endif %}


<div class="page_contents">
 <div class="pagination">
  <span class="step-links">
   {% if object_list.has_previous %}
    <a href="?page=1">&laquo;First</a>
    <a href="?page={{ object_list.previous_page_number }}">Previous</a>
   {% endif %}
    <span class="current">
     Page {{ object_list.number }}  of {{ object_list.paginator.num_pages }}.
    </span>
   {% if object_list.has_next %}
    <a href="?page={{ object_list.next_page_number }}">Next</a>
    <a href="?page={{ object_list.paginator.num_pages }}">Last &raquo;</a>
   {% endif %}
  </span>
 </div>
</div>


<div class="page_contents"><i style="font-size: 14px;">All diary notes emailed daily at 8am</i></div>
</div>

</body>

{% endblock content %}

diary/templates/diary/set_time.html
<header>Set Time</header>
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="page_contents">

{% if time_saved == "" %}

<form action="{% url "diary:set_time" %}" method="POST" name="set_time" value="set_time">{% csrf_token %}

{{ form.as_p }}

<button type="submit">Save</button>&nbsp;&nbsp;|&nbsp;&nbsp;
<button><a href="{% url "diary:home" %}">Cancel</a></button>

</form>

{% else %}

<p>{{ time_saved }}</p>
<button><a href="{% url "diary:home" %}">Back to Diary</a></button>

{% endif %}

{% if curr_time != "NOPE" %}

<p>Current send-time for emails:<br><b>{{ curr_time }}</b></p>

{% endif %}

</div>

{% endblock content %}