calco/urls.py
from django.urls import path
from . import views

app_name = "calco"

urlpatterns = [
    path("first/", views.first, name="first"),
    path("colour/", views.colour_pick, name="colour"),
    path("", views.calc1, name="calc1"),
    path("key_process/", views.key_process, name="key_process"),
    ]

django_project_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("diary/", include("diary.urls")),
    path("picnic/", include("plp.urls")),
    path("spelling/", include("spelling.urls")),
    path("calcy/", include("calco.urls")),
    #path("squares/", include("squaresg.urls")),
    path("", include("squaresg.urls")),
    
#     path("", include("squaresg.urls")),
#     path("spelling/", include("spelling.urls")),
#     path('admin/', admin.site.urls),
]

# handler404 = "squaresg.views.handler404"
# handler500 = "squaresg.views.error_500"

plp/urls.py
from django.urls import path
from . import views2

app_name = "plp"

urlpatterns = [
    path("submity/",views2.subbo, name="submity"),
    path("", views2.picn, name="index"),
    ]

calco/models.py
from django.db import models

# Create your models here.

class Colour(models.Model):
    colour_name = models.CharField(max_length=20, default="Light Grey")
    colour_hex = models.CharField(max_length=20, default="#D6DBDF")

calco/forms.py
from django import forms
from .models import Colour

# class ColourChoose(forms.ModelForm):
#     colour_list = Colour.objects.values_list("colour_name", "colour_hex")
#     COLOR_CHOICES = [i for i in colour_list]
#     colour = forms.ChoiceField(choices = COLOUR_CHOICES)

calco/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Colour
from .service import swappy, cooko, calc_prep, num_disp, cookie_default, \
     cookie_eater, font_sizer, cookie_colour


# Create your views here.

def key_process(request):
    response = HttpResponseRedirect(reverse("calco:calc1"))
    num = request.GET.get("num_id")
    if request.COOKIES["sum_list"] == "MEMORY ERROR" and num != "CLEAR":
        return response
    else:
        if len(request.COOKIES["sum_list"]) <= 29 or num == "CLEAR":
            cooky = cooko(request, num)
            response.set_cookie("sum_list", cooky)
            
            return response
        elif len(request.COOKIES["sum_list"]) > 29 and num != "CLEAR":
            response.set_cookie("sum_list", "MEMORY ERROR")
            return response
        else:
            return response

def calc1(request):    
    templ8 = cookie_default("design", request.COOKIES, "1")
    picked_colour = cookie_default("picked_colour", request.COOKIES, "#D6DBDF")
    
    template = "calco/calc{}.html".format(templ8)
    buttons = ["CLEAR", "1", "2", "3", "+", "4", "5", "6", "-", "7", "8", "9", "x", "0", \
               "(", ")", "÷", ".", "="]
    signs = ["+", "-", "*", "/", "(", ")"]
    colours = Colour.objects.values_list("colour_name", "colour_hex")
    if "colours_list" not in request.COOKIES:
        colours_list = [i for i in colours]
    else:
        colours_list = cookie_colour(request.COOKIES, "colours_list")
    
    if "sum_list" in request.COOKIES:
        final_list = request.COOKIES["sum_list"]
        
        if len(final_list) > 0 and final_list[-1] == "C":
            final_list = ""
            total = ""
            cooky = total
            sizey = font_sizer(total)
            
            response = render(request, template, {"buttons": buttons, "screen": total, \
                                                 "colours_list": colours_list, "picked_colour": picked_colour, \
                                                  "sizey": sizey})
            response.set_cookie("sum_list", cooky)
            response.set_cookie("design", templ8)
            response.set_cookie("picked_colour", picked_colour)
            response.set_cookie("colours_list", colours_list)
            cookie_eater(request.COOKIES, response)
            return response
        
        elif len(final_list) > 0 and final_list[-1] == "=":
            try:
                total = str(eval(calc_prep(final_list[:-1])))
            except (SyntaxError, NameError) as e:
                total = "ERROR"

            if total[-2:] == ".0":
                total = str(total[:-2])
            elif "." in total and total[-2:] != ".0" and len(total) > 20:
                five = total[:5]
                if "." in five:
                    total = float(total)
                    total = "{:.7f}".format(total)
                else:
                    total = total
        
            cooky = total
            sizey = font_sizer(total)
            
            response = render(request, template, {"buttons": buttons, "screen": total, \
                                                  "colours_list": colours_list, "picked_colour": picked_colour, \
                                                  "sizey": sizey})
            response.set_cookie("sum_list", cooky)
            response.set_cookie("design", templ8)
            response.set_cookie("picked_colour", picked_colour)
            response.set_cookie("colours_list", colours_list)
            cookie_eater(request.COOKIES, response)
            return response
        
        elif len(final_list) > 1 and final_list[-1] == "C":
            final_list = ""
            total = ""
        elif len(final_list) == 1 and final_list[0] == "C":
            final_list = ""
            total = ""
        elif len(final_list) == 6 and final_list[:-1] == "ERROR":
            total = final_list[-1]
            
            cooky = total
            sizey = font_sizer(total)
            response = render(request, template, {"buttons": buttons, "screen": total, \
                                                  "colours_list": colours_list, "picked_colour": picked_colour, \
                                                  "sizey": sizey})
            
            response.set_cookie("sum_list", cooky)
            response.set_cookie("design", templ8)
            response.set_cookie("picked_colour", picked_colour)
            response.set_cookie("colours_list", colours_list)
            cookie_eater(request.COOKIES, response)
            return response
        
        elif len(final_list) > 0:
            if final_list[-1] in signs:
                total = final_list[-1]
            else:
                total = num_disp(final_list)
        elif len(final_list) == 1:
            total = str(final_list)
        else:
            total = final_list
    else:
        total = ""
    sizey = font_sizer(total)
    
    response = render(request, template, {"buttons": buttons, "screen": total, \
                                          "colours_list": colours_list, "picked_colour": picked_colour, \
                                          "sizey": sizey})
    cooky = cooko(request, "")
    response.set_cookie("sum_list", cooky)
    response.set_cookie("design", templ8)
    response.set_cookie("picked_colour", picked_colour)
    response.set_cookie("colours_list", colours_list)
    cookie_eater(request.COOKIES, response)
    return response
    
def first(request):
    if "design" in request.COOKIES:
        templ8 = request.COOKIES["design"]
    templ8 = request.GET.get("templ8", "1")    
    if "picked_colour" in request.COOKIES:
        picked = request.COOKIES["picked_colour"]
    else:
        picked = "#D6DBDF"
    response = HttpResponseRedirect(reverse("calco:calc1"))
    response.set_cookie("design", templ8)
    response.set_cookie("picked_colour", picked)
    return response

def colour_pick(request):
    pick = request.GET.get("coloury")
    if "picked_colour" in request.COOKIES:
        if pick == "":
            colour = request.COOKIES["picked_colour"]
        elif pick != "":
            colour = pick
        else:
            colour = "#D6DBDF"
    else:
        if pick:
            colour = pick
        else:
            colour = "#D6DBDF"
    response = HttpResponseRedirect(reverse("calco:calc1"))
    response.set_cookie("picked_colour", colour)
    return response

calco/templates/calco/calc1.html
<header>Calculator 1</header>
{% extends "base.html" %}
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>


{% block content %}
<body>

<div class="calc_swap">
Calc 1&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="{% url "calco:first" %}?templ8={{ "2" | urlencode }}" id="swap_links">Calc 2</a>&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="{% url "calco:first" %}?templ8={{ "3" | urlencode }}" id="swap_links">Calc 3</a>
</div>

<div class="calculator1" style="background-color: {{ picked_colour }};">

	<div class="screen-itself1">

<span class="screen1" style="font-size: {{ sizey }};">
{% if screen == "" %}
	{{ "0" }}
{% elif screen == "ERROR" %}
	{{ "ERROR" }}
{% elif screen == "*" %}
	{{ "x" }}
{% elif screen == "/" %}
	{{ "÷" }}
{% else %}
	{{ screen }}
{% endif %}
	</span>
</div>

 		<div class="button-box">
{% for button in buttons %}

  {% if button == "CLEAR" %}
   <a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons">
		<div class="big-button">
			{{ button }}</div></a>

 {% elif button == "=" %}
  <a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons">
		<div class="buttony" id="equals-button">
			{{ button }}</div>
	</a>

  {% else %}

 <a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons">
<div class="buttony" {% if button == "(" or button == ")" %} style="padding-top: 4px; padding-bottom: 4px;" 
 {% elif button == "-" or button == "x" or button == "÷" %} style="padding-top: 4px; padding-bottom: 4px;"
 {% else %}{% endif %}>{{ button }}</div></a>
  {% endif %}
{% endfor %}
 		</div>

</div>

<div class="formypick"><form action="colour">{% csrf_token %}
<select name="coloury">
	<option value="{{ colour.1 }}">--Select Colour--</option>
{% for colour in colours_list %}
	<option value="{{ colour.1 }}">{{ colour.0 }}</option>
{% endfor %}
</select>
<input type="submit" value="Select">
</form></div>



</body>
{% endblock content %}

calco/templates/calco/calc2.html
<header>Calculator 2</header>
{% extends "base.html" %}
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>

<body>

{% block content %}

<div class="calc_swap">
<a href="{% url "calco:first" %}?templ8={{ "1" | urlencode }}" id="swap_links">Calc 1</a>&nbsp;&nbsp;|&nbsp;&nbsp;
Calc 2&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="{% url "calco:first" %}?templ8={{ "3" | urlencode }}" id="swap_links">Calc 3</a>
</div>

<div class="calculator2">

<div class="screen-itself2" style="font-size: {{ sizey }};">
	<span class="screen2">
{% if screen == "" %}
	{{ "0" }}
{% elif screen == "0" %}
	{{ "ERROR" }}
{% elif screen == "*" %}
	{{ "x" }}
{% elif screen == "/" %}
	{{ "÷" }}
{% else %}
	{{ screen }}
{% endif %}
	</span>
</div>

		<div class="button-box2">
{% for button in buttons %}


{% if button == "CLEAR" %}

 <a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons2">
	<div class="big-button2">
		{{ button }}</div></a>

{% elif button == "=" %}
 <a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons2">
	<div class="buttony2" id="equals-button2">
	{{ button }}</div></a>
{% else %}
 <a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons2">
	<div class = "buttony2" {% if button == "(" or button == ")" %} style="padding-top: 11px; padding-bottom: 13px;" {% else %}{% endif %}>
       {{ button }}
	</div></a>


 {% endif %}
{% endfor %}
		</div>
</div>

</body>
{% endblock content %}

calco/templates/calco/calc3.html
<header>Calculator 3</header>
{% extends "base.html" %}
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

</head>

{% block content %}
<body>

<div class="calc_swap">
<a href="{% url "calco:first" %}?templ8={{ "1" | urlencode }}">Calc 1</a>&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="{% url "calco:first" %}?templ8={{  "2" | urlencode}}">Calc 2</a>&nbsp;&nbsp;|&nbsp;&nbsp;
Calc 3
</div>

<div class="calculator3">
	<div class="screen-itself3">
		<div class="screen3" style="font-size: {{ sizey }};">
{% if screen == "" %}
	{{ "0" }}
{% elif screen == "0" %}
	{{ "ERROR" }}
{% elif screen == "*" %}
	{{ "x" }}
{% elif screen == "/" %}
	{{ "÷" }}
{% else %}
	{{ screen }}
{% endif %}

		</div>
	</div>

 <div class="button-box3">
{% for button in buttons %}

 {% if button == "CLEAR" %}
	<a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons3">
	<div class="big-button3">
	{{ button }}</div></a>
 {% elif button == "=" %}
  <a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons3">
   <div class="buttony3" id="equals-button3">
    {{ button }}
   </div></div></a>

{% else %}
 <a href="{% url "calco:key_process" %}?num_id={{ button | urlencode }}" id="the_buttons3">
  <div class="buttony3" {% if button == "(" or button == ")" %} style="padding-top: 3px; padding-bottom: 5px;" 
  {% elif button == "x" %} style="padding-top: 2px; padding-bottom: 6px;" 
  {% elif button == "÷" %} style="padding-top: 3px; padding-bottom: 5px;" {% else %}{% endif %}>   
    {{ button }}
  </div></a>

 {% endif %}

{% endfor %}
 </div>
</div>
</body>

{% endblock content %}